title: 'hackitmac - McMaster University'
description: 'hackitmac is a club at McMaster University created to foster a community of individuals who solve problems through the innovative use of technology.'
og_site_name: 'hackitmac'
og_title: 'hackitmac - Spring 2014'
og_image: 'http://hackitmac.org/img/hackitmac.png'
root: 'http://hackitmac.org'
safe: true
lsi: false
pygments: true
markdown: redcarpet